// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: internal/taskmanager/proto/user.proto

package userspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_internal_taskmanager_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_taskmanager_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_internal_taskmanager_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *EmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExistsResponse) Reset() {
	*x = UserExistsResponse{}
	mi := &file_internal_taskmanager_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExistsResponse) ProtoMessage() {}

func (x *UserExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_taskmanager_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExistsResponse.ProtoReflect.Descriptor instead.
func (*UserExistsResponse) Descriptor() ([]byte, []int) {
	return file_internal_taskmanager_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_internal_taskmanager_proto_user_proto protoreflect.FileDescriptor

const file_internal_taskmanager_proto_user_proto_rawDesc = "" +
	"\n" +
	"%internal/taskmanager/proto/user.proto\x12\x05users\"$\n" +
	"\fEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\",\n" +
	"\x12UserExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2Q\n" +
	"\vUserService\x12B\n" +
	"\x10HasUserWithEmail\x12\x13.users.EmailRequest\x1a\x19.users.UserExistsResponseB$Z\"internal/taskmanager/proto;userspbb\x06proto3"

var (
	file_internal_taskmanager_proto_user_proto_rawDescOnce sync.Once
	file_internal_taskmanager_proto_user_proto_rawDescData []byte
)

func file_internal_taskmanager_proto_user_proto_rawDescGZIP() []byte {
	file_internal_taskmanager_proto_user_proto_rawDescOnce.Do(func() {
		file_internal_taskmanager_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_taskmanager_proto_user_proto_rawDesc), len(file_internal_taskmanager_proto_user_proto_rawDesc)))
	})
	return file_internal_taskmanager_proto_user_proto_rawDescData
}

var file_internal_taskmanager_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_taskmanager_proto_user_proto_goTypes = []any{
	(*EmailRequest)(nil),       // 0: users.EmailRequest
	(*UserExistsResponse)(nil), // 1: users.UserExistsResponse
}
var file_internal_taskmanager_proto_user_proto_depIdxs = []int32{
	0, // 0: users.UserService.HasUserWithEmail:input_type -> users.EmailRequest
	1, // 1: users.UserService.HasUserWithEmail:output_type -> users.UserExistsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_taskmanager_proto_user_proto_init() }
func file_internal_taskmanager_proto_user_proto_init() {
	if File_internal_taskmanager_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_taskmanager_proto_user_proto_rawDesc), len(file_internal_taskmanager_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_taskmanager_proto_user_proto_goTypes,
		DependencyIndexes: file_internal_taskmanager_proto_user_proto_depIdxs,
		MessageInfos:      file_internal_taskmanager_proto_user_proto_msgTypes,
	}.Build()
	File_internal_taskmanager_proto_user_proto = out.File
	file_internal_taskmanager_proto_user_proto_goTypes = nil
	file_internal_taskmanager_proto_user_proto_depIdxs = nil
}
